FROM php:7.2-apache
MAINTAINER Seven Zhang <galaxywork@qq.com>

# all ext list https://gist.github.com/chronon/95911d21928cff786e306c23e7d1d3f3

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        supervisor \
        vim \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

RUN docker-php-ext-install -j$(nproc) mysqli \
	&& docker-php-ext-install -j$(nproc) pdo_mysql

RUN a2enmod rewrite
